#!/usr/bin/env node
// Regenerates src/renderer/shared/icons.js from the lucide-static package.
// Add an icon name to ICONS and run: node scripts/sync-icons.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ICONS = [
  'play', 'pause', 'mic', 'mic-off', 'rotate-ccw', 'folder-open', 'square-pen', 'settings-2',
  'chevron-up', 'chevron-down', 'x', 'clipboard-paste', 'chevrons-down', 'audio-lines', 'refresh-cw',
  'keyboard', 'move-diagonal-2', 'info', 'triangle-alert', 'eye-off', 'type', 'palette', 'monitor',
  'book-open-text', 'file-text', 'circle-help', 'minus', 'plus', 'sparkles', 'save', 'file-plus',
  'external-link', 'check', 'sliders-horizontal',
];

const pkg = JSON.parse(readFileSync(join(ROOT, 'node_modules', 'lucide-static', 'package.json'), 'utf8'));
const lines = [
  '// Generated by scripts/sync-icons.mjs — do not edit by hand.',
  `// Icons from Lucide v${pkg.version} (https://lucide.dev), ISC License,`,
  '// Copyright (c) Lucide Icons and Contributors. See licenses/ISC-lucide.txt.',
  '',
  'export const ICONS = {',
];
for (const name of ICONS) {
  const svg = readFileSync(join(ROOT, 'node_modules', 'lucide-static', 'icons', `${name}.svg`), 'utf8');
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'))
    .split('\n').map((l) => l.trim()).filter(Boolean).join('');
  lines.push(`  '${name}': '${inner.replace(/'/g, "\\'")}',`);
}
lines.push('};', '');
lines.push(`/** Inline SVG markup for an icon. */
export function icon(name, size = 18) {
  const body = ICONS[name] || '';
  return \`<svg class="icon" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${body}</svg>\`;
}
`);
writeFileSync(join(ROOT, 'src', 'renderer', 'shared', 'icons.js'), lines.join('\n'));
writeFileSync(join(ROOT, 'licenses', 'ISC-lucide.txt'), readFileSync(join(ROOT, 'node_modules', 'lucide-static', 'LICENSE'), 'utf8'));
console.log(`Wrote ${ICONS.length} icons.`);
